//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palindrom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorije
    {
        public int KategorijaID { get; set; }
        public string NazivKategorije { get; set; }
    }
}
